# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 03:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('bday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Phone number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
