# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.Address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bday',
            field=models.DateField(blank=True, verbose_name='Birthday'),
        ),
    ]
