# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 02:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('start_at', models.DateTimeField(verbose_name='Start')),
                ('end_at', models.DateTimeField(verbose_name='End')),
                ('confirmed', models.BooleanField(verbose_name='Confirmed?')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('departure', models.CharField(max_length=20, verbose_name='Departure airport')),
                ('arrival', models.CharField(max_length=20, verbose_name='Arrival airport')),
                ('airline', models.CharField(blank=True, max_length=20, verbose_name='Airline')),
                ('flight_no', models.IntegerField(blank=True, verbose_name='Flight number')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.Calendar', verbose_name='Calendar')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'ordering': ['-start_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('start_at', models.DateTimeField(verbose_name='Start')),
                ('end_at', models.DateTimeField(verbose_name='End')),
                ('confirmed', models.BooleanField(verbose_name='Confirmed?')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.Calendar', verbose_name='Calendar')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'ordering': ['-start_at'],
                'abstract': False,
            },
        ),
    ]
