# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 21:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('start_at', models.DateTimeField(verbose_name='Start')),
                ('end_at', models.DateTimeField(verbose_name='End')),
                ('confirmed', models.BooleanField(verbose_name='Confirmed?')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.Calendar', verbose_name='Calendar')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
        ),
    ]
