# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Airline'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Flight number'),
        ),
    ]
