# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170304_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_at']},
        ),
    ]
