# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('members', models.ManyToManyField(related_name='calendars_shared', to=settings.AUTH_USER_MODEL, verbose_name='Shared with')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars_owned', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
        ),
    ]
