# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='members',
            field=models.ManyToManyField(related_name='calendars_shared', to='profiles.Profile', verbose_name='Shared with'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars_owned', to='profiles.Profile', verbose_name='Created by'),
        ),
    ]
