# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 02:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memberships', '0001_initial'),
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='calendars_shared', through='memberships.Membership', to=settings.AUTH_USER_MODEL, verbose_name='Shared with'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars_owned', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
