# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_auto_20170309_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='calendars_shared', through='memberships.Membership', to=settings.AUTH_USER_MODEL, verbose_name='Shared with'),
        ),
    ]
