# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_auto_20170304_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='members',
            field=models.ManyToManyField(related_name='calendars_shared', to='profiles.Profile', verbose_name='Shared with'),
        ),
    ]
