# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='color_hex',
            field=models.CharField(max_length=7, verbose_name='Color'),
        ),
    ]
